# Mapas descritivos usando a base de dados da CETESB

### Leitura das bases de dados
### Merge com dados georreferenciados

In [2]:
%pip install geopandas

Requirement already satisfied: geopandas in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from geopandas) (2.4.2)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python314\site-packages (from geopandas) (26.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from geopandas) (3.0.0)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python314\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: certifi in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.1.4)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
# Manipulação de dados
import pandas as pd

# Visualização de dataframe
from IPython.display import display

# Confecção de plots
import matplotlib.pyplot as plt
import seaborn as sns

# Manipulação de dados geográficos
import geopandas as gpd

In [45]:
# Função de visualização de dataframes

def df_visualization(df):
    print(f'Formato: {df.shape}\n\nInformações:')
    print(df.info())
    display(df.head(2))


# Função de fazer uma soma de dados agregados de um dataframe
def sum_aggregate_function(df, indice1, indice2, col_somada):
    if indice2 != 0:
        x = df.groupby([indice1] + indice2)[col_somada].sum()
    elif indice2 == 0:
        x = df.groupby(indice1)[col_somada].sum()
    
    return x

In [5]:
# Criação do dataframe 'cru'
excel_path = 'C:/Users/User/Documents/Códigos Github/cetesb-contaminant-study/notebooks/areas_contaminadas_modelagem.xlsx'
df = pd.read_excel(excel_path)
df = pd.DataFrame(df)

# Visualização inicial do dataframe
df_visualization(df)

Formato: (7141, 139)

Informações:
<class 'pandas.DataFrame'>
RangeIndex: 7141 entries, 0 to 7140
Columns: 139 entries, OBJECTID to medida_remediacao__tratamento_termico_in_situ
dtypes: bool(1), datetime64[us](2), float64(5), int64(106), str(25)
memory usage: 7.5 MB
None

,OBJECTID,NIS,IdMunSipol,NomeEmpree,AtividadeSipol,TipoEmpree,ClassificacaoAtual,DataClassificacao,NomMunicipio,CodIBGE,...,medida_remediacao__fitorremediacao,medida_remediacao__lavagem_de_solo,medida_remediacao__outras,medida_remediacao__oxidacao_quimica,medida_remediacao__recuperacao_de_fase_livre,medida_remediacao__reducao_quimica,medida_remediacao__remocao_de_solo_residuo,medida_remediacao__sem_medidas_de_remediacao,medida_remediacao__solo_contaminado,medida_remediacao__tratamento_termico_in_situ
0,1,1,100,AUTO POSTO PIRITUBANO LTDA,Combustíveis e lubrificantes para veículos; co...,Sem Tipologia Específica,Área Contaminada em Processo de Remediação (ACRe),1225508400000,SÃO PAULO,3550308,...,0,0,0,0,0,0,0,0,0,0
1,2,2,100,CONDOMÍNIO LUMINA PARQUE CLUBE (MARSHALL EMPR....,desconhecido,desconhecido,Área Reabilitada para o Uso Declarado (AR),1739462309000,SÃO PAULO,3550308,...,0,0,0,0,0,0,1,0,0,0

In [6]:
# Retirada de colunas indesejadas
cols_to_drop = ['OBJECTID',	'NIS', 'IdMunSipol']
df = df.drop(columns=cols_to_drop)
df_visualization(df)

Formato: (7141, 136)

Informações:
<class 'pandas.DataFrame'>
RangeIndex: 7141 entries, 0 to 7140
Columns: 136 entries, NomeEmpree to medida_remediacao__tratamento_termico_in_situ
dtypes: bool(1), datetime64[us](2), float64(5), int64(104), str(24)
memory usage: 7.4 MB
None

,NomeEmpree,AtividadeSipol,TipoEmpree,ClassificacaoAtual,DataClassificacao,NomMunicipio,CodIBGE,Latitude,Longitude,GrupoContaminante,...,medida_remediacao__fitorremediacao,medida_remediacao__lavagem_de_solo,medida_remediacao__outras,medida_remediacao__oxidacao_quimica,medida_remediacao__recuperacao_de_fase_livre,medida_remediacao__reducao_quimica,medida_remediacao__remocao_de_solo_residuo,medida_remediacao__sem_medidas_de_remediacao,medida_remediacao__solo_contaminado,medida_remediacao__tratamento_termico_in_situ
0,AUTO POSTO PIRITUBANO LTDA,Combustíveis e lubrificantes para veículos; co...,Sem Tipologia Específica,Área Contaminada em Processo de Remediação (ACRe),1225508400000,SÃO PAULO,3550308,-23.489584,-46.729475,COMBUSTÍVEIS AUTOMOTIVOS/SOLVENTES AROMÁTICOS/...,...,0,0,0,0,0,0,0,0,0,0
1,CONDOMÍNIO LUMINA PARQUE CLUBE (MARSHALL EMPR....,desconhecido,desconhecido,Área Reabilitada para o Uso Declarado (AR),1739462309000,SÃO PAULO,3550308,-23.538077,-46.590618,METAIS/PAHs/Grupo TPH/CONTAMINANTES,...,0,0,0,0,0,0,1,0,0,0

In [7]:
# Leitura e visualização do shapefile de SP
shape_path = "C:/Users/User/Documents/Códigos Github/cetesb-contaminant-study/SP_Municipios_2024/SP_Municipios_2024.shp"
geo_df = gpd.read_file(shape_path)
df_visualization(geo_df)

Formato: (645, 16)

Informações:
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CD_MUN    645 non-null    str
 1   NM_MUN    645 non-null    str
 2   CD_RGI    645 non-null    str
 3   NM_RGI    645 non-null    str
 4   CD_RGINT  645 non-null    str
 5   NM_RGINT  645 non-null    str
 6   CD_UF     645 non-null    str
 7   NM_UF     645 non-null    str
 8   SIGLA_UF  645 non-null    str
 9   CD_REGIA  645 non-null    str
 10  NM_REGIA  645 non-null    str
 11  SIGLA_RG  645 non-null    str
 12  CD_CONCU  180 non-null    str
 13  NM_CONCU  180 non-null    str
 14  AREA_KM2  645 non-null    float64
 15  geometry  645 non-null    geometry
dtypes: float64(1), geometry(1), str(14)
memory usage: 80.8 KB
None

,CD_MUN,NM_MUN,CD_RGI,NM_RGI,CD_RGINT,NM_RGINT,CD_UF,NM_UF,SIGLA_UF,CD_REGIA,NM_REGIA,SIGLA_RG,CD_CONCU,NM_CONCU,AREA_KM2,geometry
0,3513009,Cotia,350001,São Paulo,3501,São Paulo,35,São Paulo,SP,3,Sudeste,SE,3550308,São Paulo/SP,323.994,"POLYGON ((-46.91759 -23.65551, -46.91764 -23.6..."
1,3532827,Nova Campina,350004,Itapeva,3502,Sorocaba,35,São Paulo,SP,3,Sudeste,SE,NaN,NaN,385.375,"POLYGON ((-48.89989 -24.10036, -48.87064 -24.1..."

In [8]:
# Certificando que o nome e tipo de dado de CD_MUN seja o mesmo do que CodIBGE
geo_df = geo_df.rename(columns={'CD_MUN': 'CodIBGE'})
geo_df['CodIBGE'] = geo_df['CodIBGE'].astype(int)
geo_df = geo_df[['CodIBGE', 'geometry']]

# Merge (equivalente a um left join) para inserir dados georreferenciados no dataframe
geo_df = df.merge(geo_df, how='left', left_on='CodIBGE', right_on='CodIBGE')


df_visualization(geo_df)

Formato: (7141, 137)

Informações:
<class 'pandas.DataFrame'>
RangeIndex: 7141 entries, 0 to 7140
Columns: 137 entries, NomeEmpree to geometry
dtypes: bool(1), datetime64[us](2), float64(5), geometry(1), int64(104), str(24)
memory usage: 7.4 MB
None

,NomeEmpree,AtividadeSipol,TipoEmpree,ClassificacaoAtual,DataClassificacao,NomMunicipio,CodIBGE,Latitude,Longitude,GrupoContaminante,...,medida_remediacao__lavagem_de_solo,medida_remediacao__outras,medida_remediacao__oxidacao_quimica,medida_remediacao__recuperacao_de_fase_livre,medida_remediacao__reducao_quimica,medida_remediacao__remocao_de_solo_residuo,medida_remediacao__sem_medidas_de_remediacao,medida_remediacao__solo_contaminado,medida_remediacao__tratamento_termico_in_situ,geometry
0,AUTO POSTO PIRITUBANO LTDA,Combustíveis e lubrificantes para veículos; co...,Sem Tipologia Específica,Área Contaminada em Processo de Remediação (ACRe),1225508400000,SÃO PAULO,3550308,-23.489584,-46.729475,COMBUSTÍVEIS AUTOMOTIVOS/SOLVENTES AROMÁTICOS/...,...,0,0,0,0,0,0,0,0,0,"POLYGON ((-46.61631 -23.87255, -46.61632 -23.8..."
1,CONDOMÍNIO LUMINA PARQUE CLUBE (MARSHALL EMPR....,desconhecido,desconhecido,Área Reabilitada para o Uso Declarado (AR),1739462309000,SÃO PAULO,3550308,-23.538077,-46.590618,METAIS/PAHs/Grupo TPH/CONTAMINANTES,...,0,0,0,0,0,1,0,0,0,"POLYGON ((-46.61631 -23.87255, -46.61632 -23.8..."

In [9]:
# Listando as colunas dummies para facilitar agrupamentos
cols_contaminantes = [col for col in geo_df.columns if col.startswith('grupo_contaminante_')]
cols_atividades = [col for col in geo_df.columns if col.startswith('grupo_atividade_')]
cols_fontes = [col for col in geo_df.columns if col.startswith('fonte_contaminacao')]
cols_meios = [col for col in geo_df.columns if col.startswith('meio_impactado')]

# Visualização da quantidade de elementos em cada lista
print(f'Grupos de contaminantes: {len(cols_contaminantes)}\n'
      f'Grupos de atividades: {len(cols_atividades)}\n'
      f'Fontes de contaminação: {len(cols_fontes)}\n'
      f'Meios impactados: {len(cols_meios)}\n')

Grupos de contaminantes: 22
Grupos de atividades: 12
Fontes de contaminação: 10
Meios impactados: 24

In [ ]:
# Agregação das informações por município
    # Contaminantes
contaminantes_per_mun = sum_aggregate_function(geo_df, 'NomMunicipio', 0, cols_contaminantes)
    # Fontes de Contaminação
fontes_per_mun = sum_aggregate_function(geo_df, 'NomMunicipio', 0, cols_fontes)
    # Meios Impactados
meio_per_mun = sum_aggregate_function(geo_df, 'NomMunicipio', 0, cols_meios)
    # Grupos de Atividade
atividade_per_mun = sum_aggregate_function(geo_df, 'NomMunicipio', 0, cols_atividades)



# Agregação das informações por município e atividade
    # Contaminantes
contaminantes_per_atv = sum_aggregate_function(geo_df, 'NomMunicipio', cols_atividades, cols_contaminantes)
    # Fontes de Contaminação
fontes_per_atv = sum_aggregate_function(geo_df, 'NomMunicipio', cols_atividades, cols_fontes)
    # Meios Impactados
meio_per_atv = sum_aggregate_function(geo_df, 'NomMunicipio', cols_atividades, cols_meios)

# Visualização da agregação por município
display(contaminantes_per_mun.sort_values(by=cols_contaminantes).tail(1))
display(fontes_per_mun.sort_values(by=cols_fontes).tail(1))
display(meio_per_mun.sort_values(by=cols_meios).tail(1))
display(atividade_per_mun.sort_values(by=cols_atividades).tail(1))

print(
    f'\n----------------------------------------------------------------'
    '--------------------------------------------------------------------------------------'
    f'\nSegunda leva de dataframes:\n'
    f'------------------------------------------------------------------'
    '--------------------------------------------------------------------------------------\n')

# Visualização da agregação por município E atividade
display(contaminantes_per_atv.sort_values(by=cols_contaminantes).tail(1))
display(fontes_per_atv.sort_values(by=cols_fontes).tail(1))
display(meio_per_atv.sort_values(by=cols_meios).tail(1))

,grupo_contaminante__anilinas,grupo_contaminante__biocidas,grupo_contaminante__combustiveis_automotivos,grupo_contaminante__contaminantes,grupo_contaminante__dioxinas_e_furanos,grupo_contaminante__fenois,grupo_contaminante__ftalatos,grupo_contaminante__gases,grupo_contaminante__grupo_tph,grupo_contaminante__metais,...,grupo_contaminante__outros_inorganicos,grupo_contaminante__outros_vapores,grupo_contaminante__pahs,grupo_contaminante__pcbs,grupo_contaminante__pops,grupo_contaminante__radionuclideos,grupo_contaminante__solventes_aromaticos,grupo_contaminante__solventes_aromaticos_halogenados,grupo_contaminante__solventes_halogenados,grupo_contaminante__desconhecido
NomMunicipio,,,,,,,,,,,,,,,,,,,,,
SÃO PAULO,5,11,1720,51,5,20,15,25,375,539,...,43,25,1049,75,33,3,1587,38,295,188

,fonte_contaminacao__acidentes,fonte_contaminacao__armazenagem,fonte_contaminacao__descartes,fonte_contaminacao__desconhecida,fonte_contaminacao__emissoes_atmosfericas,fonte_contaminacao__infiltracao,fonte_contaminacao__manutencao,fonte_contaminacao__producao,fonte_contaminacao__tratamento_de_efluentes,fonte_contaminacao__desconhecido
NomMunicipio,,,,,,,,,,
SÃO PAULO,20,1912,121,125,2,98,90,407,17,205

,meio_impactado__ar_ambiente,meio_impactado__ar_ambiente_dentro,meio_impactado__ar_ambiente_fora,meio_impactado__ar_do_solo,meio_impactado__ar_do_solo_dentro,meio_impactado__ar_do_solo_fora,meio_impactado__biota,meio_impactado__biota_dentro,meio_impactado__biota_fora,meio_impactado__sedimentos_dentro,...,meio_impactado__subsolo,meio_impactado__subsolo_dentro,meio_impactado__subsolo_fora,meio_impactado__desconhecido,meio_impactado__aguas_subterraneas,meio_impactado__aguas_subterraneas_dentro,meio_impactado__aguas_subterraneas_fora,meio_impactado__aguas_superficiais,meio_impactado__aguas_superficiais_dentro,meio_impactado__aguas_superficiais_fora
NomMunicipio,,,,,,,,,,,,,,,,,,,,,
SÃO PAULO,3,12,0,35,73,8,0,0,0,3,...,196,1053,9,206,2020,207,6,10,0,1

,grupo_atividade_geral_lista,grupo_atividade_geral,grupo_atividade_geral_multiplo,grupo_atividade_segmento,grupo_atividade__acidentes,grupo_atividade__cemiterio,grupo_atividade__comercio,grupo_atividade__desconhecido,grupo_atividade__industria,grupo_atividade__outros,grupo_atividade__posto_de_gasolina,grupo_atividade__areas_de_disposicao_de_residuo
NomMunicipio,,,,,,,,,,,,
GUAREÍ,['Áreas de disposição de Resíduo']['Posto de G...,Áreas de disposição de ResíduoPosto de Gasolin...,0,Áreas de disposição de ResíduoPosto de Gasolin...,0,0,0,0,0,0,3,3

------------------------------------------------------------------------------------------------------------------------------------------------------
Segunda leva de dataframes:
--------------------------------------------------------------------------------------------------------------------------------------------------------

,,,,,,,,,,,,,grupo_contaminante__anilinas,grupo_contaminante__biocidas,grupo_contaminante__combustiveis_automotivos,grupo_contaminante__contaminantes,grupo_contaminante__dioxinas_e_furanos,grupo_contaminante__fenois,grupo_contaminante__ftalatos,grupo_contaminante__gases,grupo_contaminante__grupo_tph,grupo_contaminante__metais,...,grupo_contaminante__outros_inorganicos,grupo_contaminante__outros_vapores,grupo_contaminante__pahs,grupo_contaminante__pcbs,grupo_contaminante__pops,grupo_contaminante__radionuclideos,grupo_contaminante__solventes_aromaticos,grupo_contaminante__solventes_aromaticos_halogenados,grupo_contaminante__solventes_halogenados,grupo_contaminante__desconhecido
NomMunicipio,grupo_atividade_geral_lista,grupo_atividade_geral,grupo_atividade_geral_multiplo,grupo_atividade_segmento,grupo_atividade__acidentes,grupo_atividade__cemiterio,grupo_atividade__comercio,grupo_atividade__desconhecido,grupo_atividade__industria,grupo_atividade__outros,grupo_atividade__posto_de_gasolina,grupo_atividade__areas_de_disposicao_de_residuo,,,,,,,,,,,,,,,,,,,,,
SÃO PAULO,['Indústria'],Indústria,False,Indústria,0,0,0,0,1,0,0,0,3,8,44,24,2,15,8,13,134,362,...,27,13,130,40,19,2,152,27,233,50

,,,,,,,,,,,,,fonte_contaminacao__acidentes,fonte_contaminacao__armazenagem,fonte_contaminacao__descartes,fonte_contaminacao__desconhecida,fonte_contaminacao__emissoes_atmosfericas,fonte_contaminacao__infiltracao,fonte_contaminacao__manutencao,fonte_contaminacao__producao,fonte_contaminacao__tratamento_de_efluentes,fonte_contaminacao__desconhecido
NomMunicipio,grupo_atividade_geral_lista,grupo_atividade_geral,grupo_atividade_geral_multiplo,grupo_atividade_segmento,grupo_atividade__acidentes,grupo_atividade__cemiterio,grupo_atividade__comercio,grupo_atividade__desconhecido,grupo_atividade__industria,grupo_atividade__outros,grupo_atividade__posto_de_gasolina,grupo_atividade__areas_de_disposicao_de_residuo,,,,,,,,,,
SÃO PAULO,['Posto de Gasolina'],Posto de Gasolina,False,Posto de Gasolina,0,0,0,0,0,0,1,0,6,1669,3,3,0,22,9,0,0,31

,,,,,,,,,,,,,meio_impactado__ar_ambiente,meio_impactado__ar_ambiente_dentro,meio_impactado__ar_ambiente_fora,meio_impactado__ar_do_solo,meio_impactado__ar_do_solo_dentro,meio_impactado__ar_do_solo_fora,meio_impactado__biota,meio_impactado__biota_dentro,meio_impactado__biota_fora,meio_impactado__sedimentos_dentro,...,meio_impactado__subsolo,meio_impactado__subsolo_dentro,meio_impactado__subsolo_fora,meio_impactado__desconhecido,meio_impactado__aguas_subterraneas,meio_impactado__aguas_subterraneas_dentro,meio_impactado__aguas_subterraneas_fora,meio_impactado__aguas_superficiais,meio_impactado__aguas_superficiais_dentro,meio_impactado__aguas_superficiais_fora
NomMunicipio,grupo_atividade_geral_lista,grupo_atividade_geral,grupo_atividade_geral_multiplo,grupo_atividade_segmento,grupo_atividade__acidentes,grupo_atividade__cemiterio,grupo_atividade__comercio,grupo_atividade__desconhecido,grupo_atividade__industria,grupo_atividade__outros,grupo_atividade__posto_de_gasolina,grupo_atividade__areas_de_disposicao_de_residuo,,,,,,,,,,,,,,,,,,,,,
SÃO PAULO,['Comércio'],Comércio,False,Comércio,0,0,1,0,0,0,0,0,2,2,0,2,15,1,0,0,0,0,...,20,65,2,28,114,18,1,2,0,0